#!/usr/bin/env python3
"""
QA Rhind 2/n Unit Fraction Cert [315] — validator

Primary sources:
  Chace, A.B. (1927) The Rhind Mathematical Papyrus, Mathematical Association
    of America, Vol. 1-2. (canonical 2/n table, pp.7-13 vol.1)
  Gillings, R.J. (1972) Mathematics in the Time of the Pharaohs, MIT Press,
    ISBN 978-0-486-24315-3, Ch.6 (2/n table analysis, pp.45-80).
  Iverson, B. (1975-1996) Quantum Arithmetic vols 1-2, QA-1/QA-2.

QA mapping: The Rhind Mathematical Papyrus (c.1550 BCE, Thebes) opens with
a table of 50 unit-fraction decompositions of 2/n for odd n=3..101. Every
entry is exact rational arithmetic -- no approximations, no irrationals.
This is the earliest known systematic Q-layer computation: the scribes
were implicitly performing modular classification without naming it.

The 3-divisibility (Satellite/Singularity orbit family) partitions the table:

  Satellite/Singularity (3|n, n in {3,9,15,...,99}): 17 entries.
    ALL use the mechanical formula 2/(3k) = 1/(2k) + 1/(6k).
    This is a 2-term decomposition generated by a single algebraic rule.

  Cosmos (3 does not divide n): 33 entries.
    Mix of 2-term (12), 3-term (13), and 4-term (8).
    4-term decompositions arise ONLY in the Cosmos.

T-step (A1 compliant): qa_step from qa_orbit_rules.
Orbit family: orbit_family on (dr(n), dr(n), 9) from qa_orbit_rules,
  where dr(n) = digital root = ((n-1) % 9) + 1 in {1,...,9}.

Five claims:
  C1  Exact arithmetic: all 50 Rhind 2/n entries sum to exactly 2/n as
      Python Fraction; no float arithmetic at any step; Egyptian Q-layer
      computation verified.
  C2  Satellite 2-term: for all n with 3|n (orbit_family on (dr(n),dr(n),9)
      in {satellite,singularity}), the Rhind decomposition has exactly 2
      unit fractions; there are exactly 17 such n in {3,...,101}.
  C3  3-divisor formula: for all 17 Satellite/Singularity n=3k, the Rhind
      decomposition equals the formula 2/(3k)=1/(2k)+1/(6k) exactly
      (denominators match, not just sum value).
  C4  Cosmos 4-term exclusivity: all 4-term Rhind decompositions occur only
      for Cosmos n (3 does not divide n); there are exactly 8 such n:
      {29,43,61,73,79,83,89,101}; zero Satellite or Singularity n has 4 terms.
  C5  Theorem NT: the unit fraction notation, hieroglyphic form, and
      physical scribal layout of the Rhind 2/n table are observer projections;
      orbit_family on (dr(n),dr(n),9), exact Fraction sums, term count, and
      the 3-divisor formula are the discrete QA claims; no float state.
"""

QA_COMPLIANCE = (
    "cert_validator -- A1 no-zero arithmetic via qa_step; "
    "canonical orbit_family on (dr(n),dr(n),9) from qa_orbit_rules; "
    "Fraction arithmetic for unit-fraction sums; Theorem NT Rhind observer"
)

import json
import sys
from fractions import Fraction
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from qa_orbit_rules import orbit_family  # noqa: E402

# ── Rhind 2/n table (Chace 1927; Gillings 1972) ────────────────────────────
# Keyed by n (odd, 3..101). Value: tuple of unit-fraction denominators.
RHIND = {
    3:   (2, 6),
    5:   (3, 15),
    7:   (4, 28),
    9:   (6, 18),
    11:  (6, 66),
    13:  (8, 52, 104),
    15:  (10, 30),
    17:  (12, 51, 68),
    19:  (12, 76, 114),
    21:  (14, 42),
    23:  (12, 276),
    25:  (15, 75),
    27:  (18, 54),
    29:  (24, 58, 174, 232),
    31:  (20, 124, 155),
    33:  (22, 66),
    35:  (30, 42),
    37:  (24, 111, 296),
    39:  (26, 78),
    41:  (24, 246, 328),
    43:  (42, 86, 129, 301),
    45:  (30, 90),
    47:  (30, 141, 470),
    49:  (28, 196),
    51:  (34, 102),
    53:  (30, 318, 795),
    55:  (30, 330),
    57:  (38, 114),
    59:  (36, 236, 531),
    61:  (40, 244, 488, 610),
    63:  (42, 126),
    65:  (39, 195),
    67:  (40, 335, 536),
    69:  (46, 138),
    71:  (40, 568, 710),
    73:  (60, 219, 292, 365),
    75:  (50, 150),
    77:  (44, 308),
    79:  (60, 237, 316, 790),
    81:  (54, 162),
    83:  (60, 332, 415, 498),
    85:  (51, 255),
    87:  (58, 174),
    89:  (60, 356, 534, 890),
    91:  (70, 130),
    93:  (62, 186),
    95:  (60, 380, 570),
    97:  (56, 679, 776),
    99:  (66, 198),
    101: (101, 202, 303, 606),
}

assert len(RHIND) == 50, f"Expected 50 entries, got {len(RHIND)}"


def digital_root(n: int) -> int:
    return ((n - 1) % 9) + 1


def rhind_sum(n: int) -> Fraction:
    return sum(Fraction(1, d) for d in RHIND[n])


checks = {}
passed = 0
failed = 0

# C1 -- Exact arithmetic: all 50 entries sum to exactly 2/n as Fraction
failures_c1 = [
    n for n in RHIND
    if rhind_sum(n) != Fraction(2, n)
]
ok_c1 = len(failures_c1) == 0 and len(RHIND) == 50
checks["C1_exact_fraction_all_50_entries"] = "PASS" if ok_c1 else "FAIL"
if ok_c1: passed += 1
else:     failed += 1

# C2 -- Satellite 2-term: all n with 3|n have exactly 2 unit fractions
satellite_n = [n for n in sorted(RHIND) if n % 3 == 0]
cosmos_n    = [n for n in sorted(RHIND) if n % 3 != 0]
ok_c2 = (
    len(satellite_n) == 17
    and all(
        orbit_family(digital_root(n), digital_root(n), 9) in ("satellite", "singularity")
        for n in satellite_n
    )
    and all(len(RHIND[n]) == 2 for n in satellite_n)
)
checks["C2_satellite_2term_17_entries"] = "PASS" if ok_c2 else "FAIL"
if ok_c2: passed += 1
else:     failed += 1

# C3 -- 3-divisor formula: Rhind denominators for n=3k equal (2k, 6k) exactly
formula_failures = []
for n in satellite_n:
    k = n // 3
    expected = (2 * k, 6 * k)
    if RHIND[n] != expected:
        formula_failures.append((n, RHIND[n], expected))
ok_c3 = len(formula_failures) == 0
checks["C3_3divisor_formula_2over3k_eq_1over2k_plus_1over6k"] = "PASS" if ok_c3 else "FAIL"
if ok_c3: passed += 1
else:     failed += 1

# C4 -- 4-term decompositions appear only in Cosmos; exactly 8 such n
four_term_n = [n for n in sorted(RHIND) if len(RHIND[n]) == 4]
four_term_in_satellite = [n for n in four_term_n if n % 3 == 0]
ok_c4 = (
    len(four_term_n) == 8
    and four_term_in_satellite == []
    and all(orbit_family(digital_root(n), digital_root(n), 9) == "cosmos"
            for n in four_term_n)
    and sorted(four_term_n) == [29, 43, 61, 73, 79, 83, 89, 101]
)
checks["C4_4term_cosmos_only_8_entries_29_43_61_73_79_83_89_101"] = "PASS" if ok_c4 else "FAIL"
if ok_c4: passed += 1
else:     failed += 1

# C5 -- Theorem NT: all denominators are integers; no float; orbit_family
#        returns strings (discrete); Fraction arithmetic never touches float
denom_types_ok = all(
    isinstance(d, int) and d > 0
    for n in RHIND for d in RHIND[n]
)
orbit_types_ok = all(
    isinstance(orbit_family(digital_root(n), digital_root(n), 9), str)
    for n in RHIND
)
ok_c5 = denom_types_ok and orbit_types_ok and all(
    isinstance(rhind_sum(n), Fraction) for n in RHIND
)
checks["C5_theorem_nt_all_denominators_int_orbit_str_sum_fraction"] = "PASS" if ok_c5 else "FAIL"
if ok_c5: passed += 1
else:     failed += 1

print(json.dumps(checks, indent=2))
print(f"\nTotal: {passed} PASS, {failed} FAIL")
if failed:
    sys.exit(1)
