#!/usr/bin/env python3
"""
Validator for QA_CONGRUENCE_SECTOR_LABEL_CERT.v1

This cert family is the "quotient-safe" counterpart to the kernel-collision cert:
it certifies that a label L defined on PSL2(Z/NZ) is a *class function* (conjugacy invariant)
and hence eligible to define congruence sectors / finite-quotient spectral projections.

Usage:
  python qa_congruence_sector_label_cert_v1/validator.py --demo
  python qa_congruence_sector_label_cert_v1/validator.py <cert.json>
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Callable, Dict, List, Tuple

# Ensure repo root is importable when running from this subdirectory.
REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from qa_resonance_spectral_experiment import (  # noqa: E402
    Mat2,
    digital_root_9,
    mod_psl_normal_form,
    reduce_mod_n,
    mul_mod_n,
    inv_mod_n,
    conj_mod_n,
    S,
    T,
    T_INV,
)


SCHEMA_ID = "QA_CONGRUENCE_SECTOR_LABEL_CERT.v1"


Label = Tuple[int, int]
ModMat = Tuple[int, int, int, int]


def _label_from_int(x: int) -> Label:
    return (x % 24, digital_root_9(x))


def label_trace2_mod72(x: ModMat, n: int) -> Label:
    a, b, c, d = x
    tr = (a + d) % n
    t2 = (tr * tr) % n
    return _label_from_int(t2)


def label_disc_mod72(x: ModMat, n: int) -> Label:
    a, b, c, d = x
    tr = (a + d) % n
    t2 = (tr * tr) % n
    disc = (t2 - 4) % n
    return _label_from_int(disc)


LABELS: Dict[str, Callable[[ModMat, int], Label]] = {
    "trace2_mod72": label_trace2_mod72,
    "disc_mod72": label_disc_mod72,
}


def factorize(n: int) -> Dict[int, int]:
    if n <= 0:
        raise ValueError("n must be positive")
    out: Dict[int, int] = {}
    d = 2
    x = n
    while d * d <= x:
        while x % d == 0:
            out[d] = out.get(d, 0) + 1
            x //= d
        d = 3 if d == 2 else d + 2
    if x > 1:
        out[x] = out.get(x, 0) + 1
    return out


def expected_sl2_order_prime_power(p: int, k: int) -> int:
    # |SL2(Z/p^kZ)|. For p=2, the closed form 6*2^(3k-3) matches k>=1.
    if p == 2:
        return 6 * (2 ** (3 * k - 3))
    return (p ** (3 * k - 2)) * (p * p - 1)


def expected_sl2_order(n: int) -> int:
    f = factorize(n)
    out = 1
    for p, k in f.items():
        out *= expected_sl2_order_prime_power(p, k)
    return out


def expected_psl2_order(n: int) -> int:
    sl = expected_sl2_order(n)
    # -I ≡ I mod n iff n | 2 (i.e. n ∈ {1,2}).
    return sl if n in (1, 2) else sl // 2


def bfs_generate_psl2_mod_n(n: int) -> List[ModMat]:
    """
    Enumerate subgroup generated by S,T in PSL2(Z/NZ) via BFS.
    For N=72 this is PSL2(Z/72Z).
    """
    s = reduce_mod_n(S, n)
    t = reduce_mod_n(T, n)
    u = reduce_mod_n(T_INV, n)

    gens = (s, t, u)
    seen = {mod_psl_normal_form((1 % n, 0, 0, 1 % n), n=n)}
    frontier = [next(iter(seen))]

    while frontier:
        cur = frontier.pop()
        for g in gens:
            nxt = mul_mod_n(cur, g, n=n)
            if nxt in seen:
                continue
            seen.add(nxt)
            frontier.append(nxt)

    return sorted(seen)


def verify(cert: Dict[str, Any], cert_path: Path) -> None:
    if cert.get("schema_id") != SCHEMA_ID:
        raise SystemExit(f"✗ schema_id must be {SCHEMA_ID}")

    n = int(cert["modulus_n"])
    label_name = cert["label_name"]
    if label_name not in LABELS:
        raise SystemExit(f"✗ unknown label_name: {label_name}")
    label_fn = LABELS[label_name]

    # Enumerate quotient group.
    elements = bfs_generate_psl2_mod_n(n)
    exp_order = expected_psl2_order(n)
    if len(elements) != exp_order:
        raise SystemExit(
            "✗ GROUP_ENUMERATION_INCOMPLETE "
            f"n={n} got={len(elements)} expected={exp_order}"
        )

    # Check well-definedness for PSL normalization explicitly (cheap).
    psl_fail = 0
    for x in elements:
        a, b, c, d = x
        neg = ((-a) % n, (-b) % n, (-c) % n, (-d) % n)
        x_norm = mod_psl_normal_form(x, n=n)
        neg_norm = mod_psl_normal_form(neg, n=n)
        if x_norm != neg_norm:
            raise SystemExit("✗ PSL normalization inconsistent (should not happen)")
        if label_fn(x_norm, n) != label_fn(neg_norm, n):
            psl_fail += 1

    if psl_fail:
        raise SystemExit(f"✗ PSL well-definedness violations: {psl_fail}")

    # Check class-function property by verifying invariance under conjugation by generators.
    s = reduce_mod_n(S, n)
    t = reduce_mod_n(T, n)
    u = reduce_mod_n(T_INV, n)
    conj_gens = (s, t, u)

    for x in elements:
        lx = label_fn(x, n)
        for g in conj_gens:
            y = conj_mod_n(g, x, n=n)
            if label_fn(y, n) != lx:
                raise SystemExit(
                    "✗ CLASS_FUNCTION_VIOLATION "
                    f"label={label_name} n={n} x={x} g={g} y={y} "
                    f"Lx={lx} Ly={label_fn(y, n)}"
                )

    # Emit a small distribution summary (useful diagnostic).
    dist = Counter(label_fn(x, n) for x in elements)
    top = dist.most_common(8)
    print(f"✓ OK: {cert_path} verifies class-function label on PSL2(Z/{n}Z)")
    print(f"  |PSL2(Z/{n}Z)| (generated by S,T): {len(elements)}")
    print(f"  top_labels: {top}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("cert", nargs="?", default=None)
    parser.add_argument("--demo", action="store_true")
    args = parser.parse_args()

    if args.demo:
        base = Path(__file__).resolve().parent / "examples"
        for p in sorted(base.glob("*.json")):
            with p.open() as f:
                verify(json.load(f), p)
        return 0

    if not args.cert:
        raise SystemExit("usage: validator.py <cert.json> OR --demo")

    cert_path = Path(args.cert)
    with cert_path.open() as f:
        verify(json.load(f), cert_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
