#!/usr/bin/env python3
# QA_COMPLIANCE = "observer=diffraction/structure-factor physics (Theorem NT); QA layer = the golden element M=[[0,1],[1,1]] as the INTEGER Fibonacci inflation/substitution matrix (A1); tile positions, S(q), Bragg intensities are observer-layer readouts. No float QA state."
# RT1_OBSERVER_FILE: positions, structure factors, peak-intensity fits are observer-layer readouts, not QA state.
"""
Phase I: chase the continuum golden angle as observer-layer -- where is the BROKEN SYMMETRY?

Phase H measured the q=0 aggregate coherence C(N)=|sum psi_k|^2 and found the golden angle
BOUNDED (beta~0). I wrongly read that as "no structure". But bounded q=0 coherence is the
SYMMETRIC limit -- perfect equidistribution. Structure / broken symmetry does not live at
q=0; it lives at q!=0, in the DIFFRACTION Bragg peaks. Will's point: if the golden angle
gave ONLY perfect symmetry (flat diffraction) there would be no evidence for broken
symmetry at all -- yet real matter diffracts. So we were missing the q!=0 spectrum.

The golden angle's observer-layer realization is a QUASICRYSTAL: the Fibonacci chain, whose
diffraction is PURE-POINT (sharp Bragg peaks) at the golden module Z+Z*phi -- long-range
order with NO translational symmetry. That is exactly "broken symmetry with evidence":
  * random (maximal symmetry/disorder): diffraction diffuse, NO Bragg peaks -> featureless.
  * crystal (periodic): Bragg peaks at a single integer module -> fully broken to a lattice.
  * QUASICRYSTAL (golden): Bragg peaks at Z+Z*phi (two incommensurate scales, dense set) ->
    broken continuous symmetry to quasiperiodic order; forbidden symmetry; phi intrinsic.

QA-native hook (not a stretch, a textbook identity): the Fibonacci inflation matrix is
[[1,1],[1,0]] ~ M=[[0,1],[1,1]] -- the SAME golden element M of the QA split-quaternion
order (char poly x^2=x+1). Its expanding eigenvalue phi sets the tile-length ratio; its
contracting eigenvalue psi=-1/phi sets the cut-and-project acceptance window. So the
observer-layer golden angle's broken-symmetry structure is GENERATED by M, and its Bragg
module Z+Z*phi is the ring of integers of Q(sqrt5) -- the same field as the icosian/E8/Hecke
thread. Whittaker closes the loop: a potential built as a superposition of plane waves
(Whittaker 1903-04) at these golden Bragg wavevectors IS a quasicrystalline potential --
the observer-layer "field" whose broken symmetry is the golden angle made physical.

The discriminator is rigorous and can fail: a Bragg peak intensity scales as N^2 (pure
point / long-range order); diffuse scattering scales as N. Measure the exponent.
"""
from __future__ import annotations
import numpy as np

PHI = (1.0 + np.sqrt(5.0)) / 2.0
PSI = PHI - 1.0                    # 1/phi ; contracting eigenvalue magnitude of M


def sq_modulus_sum(phases):
    """|sum exp(i*phases)|^2 without '**' (S1)."""
    z = np.exp(1j * phases).sum()
    return z.real * z.real + z.imag * z.imag


# ---------- observer-layer point sets (QA layer = integer inflation by M) ----------
def fibonacci_chain(n_min, short=1.0):
    """Fibonacci quasicrystal via the golden element M as the inflation rule L->LS, S->L
    (M=[[1,1],[1,0]] ~ [[0,1],[1,1]]). Tiles: long=phi, short=1 (ratio phi). Returns the
    observer-layer tile positions (a projection of the integer inflation word)."""
    sub = {"L": "LS", "S": "L"}
    w = "L"
    while len(w) < n_min:
        w = "".join(sub[c] for c in w)
    lengths = np.where(np.frombuffer(w.encode(), dtype=np.uint8) == ord("L"), PHI, short)
    return np.cumsum(lengths) - lengths           # left endpoints: x_n = sum(lengths[:n])


def periodic_chain(n, spacing):
    """Ordinary crystal: equal spacing -> Bragg at a single integer module."""
    return np.arange(n, dtype=float) * spacing


def random_chain(n, seed=7):
    """Disordered control (observer-layer null, NOT QA state): same two tile lengths but
    SHUFFLED -> no long-range order -> diffuse diffraction, no N^2 Bragg peaks."""
    rng = np.random.default_rng(seed)
    lengths = rng.choice([PHI, 1.0], size=n, p=[PHI / (PHI + 1), 1.0 / (PHI + 1)])
    return np.cumsum(lengths) - lengths           # left endpoints


# ---------- diffraction ----------
def diffraction(x, qs):
    """Structure factor S(q) = |sum_n exp(i q x_n)|^2 / N over a q-grid (chunked)."""
    n = len(x)
    out = np.empty(len(qs))
    for j in range(0, len(qs), 400):
        qb = qs[j:j + 400]
        z = np.exp(1j * np.outer(qb, x)).sum(axis=1)
        out[j:j + 400] = (z.real * z.real + z.imag * z.imag) / n
    return out


def find_peaks(qs, s, k=6, min_sep=0.15):
    """Top-k local maxima of S(q), separated by >= min_sep."""
    loc = (s[1:-1] > s[:-2]) & (s[1:-1] > s[2:])
    idx = np.where(loc)[0] + 1
    idx = idx[np.argsort(s[idx])[::-1]]
    peaks = []
    for i in idx:
        if all(abs(qs[i] - qs[p]) > min_sep for p in peaks):
            peaks.append(i)
        if len(peaks) == k:
            break
    return sorted(peaks, key=lambda i: qs[i])


def golden_index(ratio, lim=6):
    """Best (h,k) with (h+k*phi) ~ ratio*(h0+k0*phi); here fit ratio to (h+k*phi)/norm."""
    best = None
    for h in range(-lim, lim + 1):
        for k in range(-lim, lim + 1):
            val = h + k * PHI
            if val <= 0:
                continue
            err = abs(ratio - val)
            if best is None or err < best[0]:
                best = (err, h, k)
    return best


def peak_intensity_exponent(x, q, ns):
    """Exponent of I(N)=|sum_{n<=N} exp(i q x_n)|^2 ~ N^gamma. Bragg(pure point)=2, diffuse=1."""
    inten = np.array([sq_modulus_sum(q * x[:n]) for n in ns])
    m = inten > 0
    return float(np.polyfit(np.log(ns[m]), np.log(inten[m]), 1)[0])


def run():
    print("Phase I: golden angle as observer-layer -- broken symmetry in the q!=0 spectrum\n")
    n_tiles = 6000
    x_gold = fibonacci_chain(n_tiles)
    x_per = periodic_chain(len(x_gold), spacing=float(np.mean(np.diff(x_gold))))
    x_rand = random_chain(len(x_gold))
    print(f"[setup] Fibonacci chain: {len(x_gold)} tiles, <d>={np.mean(np.diff(x_gold)):.4f}, "
          f"L/S ratio=phi={PHI:.4f}; M eigenvalues phi={PHI:.4f}, psi=-{PSI:.4f}.\n")

    qs = np.linspace(0.02, 14.0, 4000)
    s_gold = diffraction(x_gold, qs)
    s_rand = diffraction(x_rand, qs)

    # --- 1. Bragg peaks of the golden quasicrystal (the q!=0 structure Phase H missed) ---
    pk = find_peaks(qs, s_gold, k=6)
    q1 = qs[pk[np.argmax([s_gold[p] for p in pk])]]        # strongest peak = module unit
    print("[1] golden diffraction -- strongest Bragg peaks (q!=0 structure):")
    print(f"    {'q':>8} {'S(q)/N':>10} {'q/q1':>8}  golden-module index (h+k*phi)")
    for p in pk:
        r = qs[p] / q1
        err, h, k = golden_index(r)
        print(f"    {qs[p]:8.3f} {s_gold[p]:10.3f} {r:8.4f}  ~ {h:+d}{k:+d}*phi (err {err:.3f})")

    # --- 2. rigorous discriminator: Bragg intensity scales as N^2 (pure point) ---
    ns = np.array([500, 1000, 2000, 4000, len(x_gold)])
    q_peak = q1
    q_off = q1 * 0.5 + 0.137                                 # a generic off-peak probe
    g_peak = peak_intensity_exponent(x_gold, q_peak, ns)
    g_off = peak_intensity_exponent(x_gold, q_off, ns)
    g_randpk = peak_intensity_exponent(x_rand, q_peak, ns)
    g_perpk = peak_intensity_exponent(x_per, 2 * np.pi / x_per[1], ns)
    print("\n[2] intensity scaling I(N)~N^gamma  (Bragg/pure-point gamma=2, diffuse gamma=1):")
    print(f"    golden, AT Bragg peak q={q_peak:.3f}:   gamma={g_peak:.2f}  "
          f"-> {'PURE-POINT (long-range order)' if g_peak > 1.6 else 'not Bragg'}")
    print(f"    golden, OFF peak q={q_off:.3f}:         gamma={g_off:.2f}  "
          f"-> {'diffuse/bounded' if g_off < 1.4 else 'peak'}")
    print(f"    RANDOM chain at same q={q_peak:.3f}:    gamma={g_randpk:.2f}  "
          f"-> {'diffuse (NO long-range order)' if g_randpk < 1.4 else 'ordered'}")
    print(f"    PERIODIC chain at its Bragg q:        gamma={g_perpk:.2f}  "
          f"-> {'Bragg (crystal)' if g_perpk > 1.6 else '?'}")

    # --- 3. quasi signature: two STRONGEST peaks sit at an IRRATIONAL (golden) ratio ---
    by_int = sorted(pk, key=lambda i: s_gold[i], reverse=True)
    pa, pb = by_int[0], by_int[1]                       # two strongest, distinct positions
    r2 = qs[pb] / qs[pa]
    err_int = min(abs(r2 - round(r2)), 1.0)
    err_gold = golden_index(r2)[0]
    print(f"\n[3] quasiperiodic signature: ratio of two strongest Bragg peaks "
          f"q={qs[pb]:.3f}/q={qs[pa]:.3f} = {r2:.4f}")
    print(f"    distance to nearest INTEGER = {err_int:.3f} (a rational ratio -> crystal ~0)")
    print(f"    distance to golden module Z+Z*phi = {err_gold:.3f} (irrational golden -> quasicrystal ~0)")

    # --- 4. Whittaker potential: superpose plane waves at the golden Bragg wavevectors ---
    xs = np.linspace(0, 60, 3000)
    qset = np.array([qs[p] for p in pk[:4]])
    amps = np.array([s_gold[p] for p in pk[:4]])
    V = sum(a * np.cos(q * xs) for q, a in zip(qset, amps))   # Whittaker-style superposition
    # quasiperiodic (not periodic): autocorrelation has no single period -> check recurrence
    Vn = (V - V.mean()) / (V.std() + 1e-12)
    ac = np.correlate(Vn, Vn, mode="full")[len(Vn) - 1:] / len(Vn)
    period_peak = 1 + int(np.argmax(ac[10:400])) + 9
    print(f"\n[4] Whittaker potential V(x)=sum_j A_j cos(q_j x) over the 4 golden Bragg q_j:")
    print(f"    strongest autocorrelation recurrence at lag {xs[period_peak]:.2f} with height "
          f"{ac[period_peak]:.3f} (<1 => quasiperiodic, no exact period) -- a quasicrystalline")
    print(f"    (Whittaker) potential, the golden angle made an observer-layer FIELD.")

    ok = g_peak > 1.6 and g_randpk < 1.4 and err_gold < 0.05 and err_int > 0.1
    print("\nVERDICT (broken symmetry located, data-driven):")
    print(f"  * The golden angle DOES carry broken symmetry -- at q!=0. Its observer-layer")
    print(f"    quasicrystal (Fibonacci chain) has PURE-POINT diffraction: Bragg intensity")
    print(f"    ~N^{g_peak:.2f} (=2 long-range order) at peaks sitting on the golden module")
    print(f"    Z+Z*phi (err {err_gold:.3f}), NOT integer positions (int err {err_int:.3f}). Phase H")
    print("    missed this because it only probed q=0 (the symmetric limit); the structure is")
    print("    the q!=0 spectrum -- exactly the 'evidence for broken symmetry' that must exist.")
    print(f"  * Random control is diffuse (gamma={g_randpk:.2f}, no Bragg): a featureless plenum")
    print("    would show NO peaks. The peaks ARE the broken symmetry.")
    print("  * Generated by M (golden element = Fibonacci inflation matrix): phi sets the tile")
    print("    ratio, psi the acceptance window; Bragg module = O_{Q(sqrt5)} = the icosian/E8")
    print("    field. Whittaker superposition at these q_j = the quasicrystalline potential.")
    print(f"\n  STATUS: {'coherent story holds' if ok else 'MIXED -- inspect numbers'}. The missing")
    print("  something was the register of the measurement (q=0 magnitude vs q!=0 order), not a")
    print("  missing mechanism: the golden angle's broken symmetry is QUASICRYSTALLINE long-range")
    print("  order, phi-intrinsic, M-generated, and Q(sqrt5)-valued -- observer-layer, but not")
    print("  arbitrary: it is the SAME golden structure the QA quaternion order already carries.")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(run())
