from __future__ import annotations

from dataclasses import dataclass, asdict
import json
from typing import Dict, List, Tuple

from qa_structural_algebra import (
    M_MU,
    M_SIGMA,
    QAState,
    build_report,
    eval_word_matrix,
    mat_det,
    matrix_to_list,
)


# --- Formal Hypothesis Objects ---

@dataclass(frozen=True)
class FormalHypothesis:
    hypothesis_id: str
    statement: str
    domain: str
    codomain: str
    verdict: str
    proof_obligations: Tuple[str, ...]
    obstruction: Tuple[str, ...]
    evidence: Dict[str, object]


# --- Constructive Certificates ---

def constructive_obstruction_nu_integer_matrix() -> Dict[str, object]:
    # Assume N in M_2(Z) realizes nu on all even states:
    # N*(2,0)^T=(1,0)^T and N*(0,2)^T=(0,1)^T.
    # Then first and second columns are (1/2,0)^T and (0,1/2)^T, contradiction with integrality.
    return {
        "assumption": "exists N in M_2(Z) with N*(2x,2y)^T=(x,y)^T for all x,y in Z",
        "equations": [
            "N*(2,0)^T=(1,0)^T",
            "N*(0,2)^T=(0,1)^T",
            "col_1(N)=(1/2,0)^T",
            "col_2(N)=(0,1/2)^T",
        ],
        "contradiction": "col_i(N) not in Z^2",
        "conclusion": "no N in M_2(Z) realizes nu as total integer-linear map on Z^2",
    }


def sigma_mu_embedding_hypothesis() -> FormalHypothesis:
    report = build_report()
    task_a = report["task_A"]
    task_b = report["task_B"]

    evidence = {
        "rho_sigma": task_a["rho"]["sigma"],
        "rho_mu": task_a["rho"]["mu"],
        "matrix_realization_checks": task_a["representation_exists"],
        "det_sigma": task_b["sigma"]["det"],
        "det_mu": task_b["mu"]["det"],
        "mod_gl2_checks": task_b["finite_mod_GL2_checks"],
        "mu_sigma_mu": matrix_to_list(eval_word_matrix(["mu", "sigma", "mu"])),
    }

    return FormalHypothesis(
        hypothesis_id="H_SIGMA_MU_MATRIX_EMBED",
        statement=(
            "rho: <sigma,mu> -> GL(2,Z), rho(sigma)=[[1,0],[1,1]], "
            "rho(mu)=[[0,1],[1,0]], and action(s)=rho(word)*s"
        ),
        domain="transition semigroup generated by {sigma,mu} on Z^2",
        codomain="matrix semigroup in GL(2,Z)",
        verdict="SUPPORTED",
        proof_obligations=(
            "forall s: sigma(s)=rho(sigma)*s",
            "forall s: mu(s)=rho(mu)*s",
            "forall words w1,w2: rho(w2 o w1)=rho(w2)rho(w1)",
            "det(rho(sigma))=1 and det(rho(mu))=-1",
        ),
        obstruction=(),
        evidence=evidence,
    )


def full_system_non_gl2_hypothesis() -> FormalHypothesis:
    obstruction_nu = constructive_obstruction_nu_integer_matrix()

    evidence = {
        "det_sigma": mat_det(M_SIGMA),
        "det_mu": mat_det(M_MU),
        "det_lambda_k": "det(k*I_2)=k^2",
        "nu_obstruction": obstruction_nu,
        "counterexample_lambda_2": {
            "matrix": [[2, 0], [0, 2]],
            "det": 4,
            "in_GL2Z": False,
        },
        "counterexample_lambda_0": {
            "matrix": [[0, 0], [0, 0]],
            "det": 0,
            "invertible": False,
        },
    }

    return FormalHypothesis(
        hypothesis_id="H_FULL_SYSTEM_NOT_GLGROUP",
        statement=(
            "No embedding of full generator family {sigma,mu,lambda_k,nu} into a single "
            "group action on Z^2 by 2x2 integer matrices"
        ),
        domain="partial parametric generator system on Z^2",
        codomain="group action by GL(2,Z)",
        verdict="PROVED_FALSE",
        proof_obligations=(
            "forall k with |k|!=1: lambda_k not invertible over Z^2",
            "nu is partial (domain=2Z^2)",
            "nu cannot be represented by any N in M_2(Z) as total map",
        ),
        obstruction=(
            "lambda_k exits GL(2,Z) for |k|!=1 since det=k^2 not in {+1,-1}",
            "nu requires (1/2)I on even lattice and is undefined on odd lattice",
        ),
        evidence=evidence,
    )


def partial_semigroup_embedding_hypothesis() -> FormalHypothesis:
    return FormalHypothesis(
        hypothesis_id="H_PARTIAL_RATIONAL_EMBED",
        statement=(
            "Full system embeds into semigroup/category of partial maps with rational matrices: "
            "sigma->[[1,0],[1,1]], mu->[[0,1],[1,0]], lambda_k->kI, nu->(1/2)I on domain 2Z^2"
        ),
        domain="generator family {sigma,mu,lambda_k,nu}",
        codomain="partial linear endomorphisms of Z^2 with domain predicates",
        verdict="SUPPORTED",
        proof_obligations=(
            "domain(nu)=2Z^2",
            "composition respects domain predicates",
            "all generators represented as rational-linear maps + guards",
        ),
        obstruction=(),
        evidence={
            "maps": {
                "sigma": matrix_to_list(M_SIGMA),
                "mu": matrix_to_list(M_MU),
                "lambda_k": "k*I_2",
                "nu": "(1/2)*I_2 with guard both_even",
            },
            "sample_defined_nu": {
                "input": QAState(8, 12).as_vector(),
                "output": QAState(4, 6).as_vector(),
            },
        },
    )


# --- Task E Output ---

def build_hypothesis_certificate() -> Dict[str, object]:
    hs: List[FormalHypothesis] = [
        sigma_mu_embedding_hypothesis(),
        full_system_non_gl2_hypothesis(),
        partial_semigroup_embedding_hypothesis(),
    ]

    return {
        "certificate_type": "QA_STRUCTURAL_ALGEBRA_HYPOTHESIS_v1",
        "hypotheses": [asdict(h) for h in hs],
    }


if __name__ == "__main__":
    print(json.dumps(build_hypothesis_certificate(), indent=2, sort_keys=True))
