import Mathlib.Data.ZMod.Basic
import Mathlib.Data.Matrix.Basic
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.GroupTheory.OrderOfElement
import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic
import Mathlib.Tactic
import QAFibMatrix

/-!
# Cyclic Subgroup ⟨F⟩ ≅ ℤ/24ℤ in GL₂(ZMod 9)

Lifts the Fibonacci matrix `fib_mat` (defined in `QAFibMatrix.lean`) to a unit
in the matrix ring M₂(ZMod 9), then establishes the group-theoretic structure:

- `fib_mat_unit` is a unit of `(Matrix (Fin 2) (Fin 2) (ZMod 9))ˣ`
  (via `det(F) = 8`, a unit in `ZMod 9` since `gcd(8, 9) = 1`).
- `orderOf fib_mat_unit = 24` — the Pisano period becomes the group-theoretic order.
- `|⟨F⟩| = 24` — the cyclic subgroup generated by `F` has exactly 24 elements.
- `⟨F⟩` is cyclic (trivially: generated by a single element).

## Cert references

- `[128]` Pisano period π(9) = 24 — the order statement.
- `[126]` orbit structure — the group action view of the three QA orbits.
- `[153]` singularity dominance — `det(F) ≠ 0` makes `F` a group element.
-/

-- ============================================================================
-- LIFT fib_mat TO A UNIT
-- ============================================================================

/-- The matrix inverse of `fib_mat`: `F⁻¹ = [[0,1],[1,8]]` over `ZMod 9`.

    Direct computation: `[[1,1],[1,0]] * [[0,1],[1,8]] = [[1,9],[0,1]] = I` mod 9. -/
private def fib_mat_inv_mat : Matrix (Fin 2) (Fin 2) (ZMod 9) := !![0, 1; 1, 8]

/-- `fib_mat` as a unit of the matrix ring `M₂(ZMod 9)`.

    `det(F) = 8` is a unit in `ZMod 9` (since `gcd(8, 9) = 1`), so `F` is
    invertible and belongs to `GL₂(ZMod 9) = (M₂(ZMod 9))ˣ`. -/
def fib_mat_unit : (Matrix (Fin 2) (Fin 2) (ZMod 9))ˣ :=
  ⟨fib_mat, fib_mat_inv_mat, by native_decide, by native_decide⟩

/-- The underlying matrix of `fib_mat_unit` is `fib_mat`. -/
@[simp]
theorem fib_mat_unit_val :
    (fib_mat_unit : Matrix (Fin 2) (Fin 2) (ZMod 9)) = fib_mat := rfl

-- ============================================================================
-- POWER LAWS IN THE UNIT GROUP
-- ============================================================================

/-- `F^24 = 1` in `(M₂(ZMod 9))ˣ` (lifts `fib_mat_pow_24` to the unit group). -/
theorem fib_mat_unit_pow_24 : fib_mat_unit ^ 24 = 1 := by
  apply Units.val_injective
  simp only [Units.val_pow_eq_pow_val, Units.val_one, fib_mat_unit_val]
  exact fib_mat_pow_24

/-- For all `k ∈ {1,...,23}`, `F^k ≠ 1` in `(M₂(ZMod 9))ˣ`.

    Lifts `fib_mat_order_exact` from matrix equality to unit equality. -/
theorem fib_mat_unit_order_exact :
    ∀ k : Fin 24, k.val ≠ 0 → fib_mat_unit ^ k.val ≠ 1 := by
  intro k hk heq
  have hmat : fib_mat ^ k.val = 1 := by
    have := congr_arg Units.val heq
    simp only [Units.val_pow_eq_pow_val, Units.val_one, fib_mat_unit_val] at this
    exact this
  exact fib_mat_order_exact k hk hmat

/-- `F^12 ≠ 1` in `(M₂(ZMod 9))ˣ` (needed for `orderOf` proof, prime factor `p = 2`). -/
theorem fib_mat_unit_pow_12_ne_one : fib_mat_unit ^ 12 ≠ 1 :=
  fib_mat_unit_order_exact ⟨12, by norm_num⟩ (by norm_num)

/-- `F^8 ≠ 1` in `(M₂(ZMod 9))ˣ` (needed for `orderOf` proof, prime factor `p = 3`). -/
theorem fib_mat_unit_pow_8_ne_one : fib_mat_unit ^ 8 ≠ 1 :=
  fib_mat_unit_order_exact ⟨8, by norm_num⟩ (by norm_num)

-- ============================================================================
-- MAIN THEOREM: orderOf F = 24
-- ============================================================================

/-- **The multiplicative order of `F` in `GL₂(ZMod 9)` is exactly 24** (cert [128]).

    This is the group-theoretic formulation of the Pisano period π(9) = 24:
    `F` generates a cyclic subgroup of order 24 in `(M₂(ZMod 9))ˣ`. -/
theorem fib_mat_unit_orderOf : orderOf fib_mat_unit = 24 := by
  rw [orderOf_eq_iff (by norm_num : 0 < 24)]
  refine ⟨fib_mat_unit_pow_24, fun m hm24 hm1 heq => ?_⟩
  exact fib_mat_unit_order_exact ⟨m, hm24⟩ (Nat.pos_iff_ne_zero.mp hm1) heq

-- ============================================================================
-- CYCLIC SUBGROUP ⟨F⟩
-- ============================================================================

/-- **The cyclic subgroup `⟨F⟩` has exactly 24 elements** (cert [128] / [126]).

    By `orderOf_eq_card_zpowers`, the cardinality of the subgroup generated
    by `F` equals the multiplicative order of `F`. -/
theorem fib_mat_zpowers_card :
    Fintype.card ↥(Subgroup.zpowers fib_mat_unit) = 24 := by
  rw [Fintype.card_zpowers]
  exact fib_mat_unit_orderOf

/-- **⟨F⟩ is a cyclic group** (trivially: generated by a single element).

    Any subgroup of the form `zpowers g` is cyclic — generated by `g` itself. -/
theorem fib_mat_zpowers_isCyclic : IsCyclic ↥(Subgroup.zpowers fib_mat_unit) :=
  Subgroup.isCyclic_zpowers fib_mat_unit
