#!/usr/bin/env python3
QA_COMPLIANCE = "observer=cert_validator, state_alphabet=mod9_residues"
"""QA Septenary Cert family [150] — certifies the septenary numbers
{1, 2, 4, 8, 7, 5} as the multiplicative group (Z/9Z)* and their
structural properties in QA mod-9 arithmetic.

SEPTENARY NUMBERS: the 6-element set {1, 2, 4, 5, 7, 8} generated by
repeated doubling mod 9: 1→2→4→8→7→5→1 (period 6).

Key properties:
1. GROUP: {1,2,4,5,7,8} = (Z/9Z)* = units mod 9 (elements coprime to 9)
2. CYCLE: doubling mod 9 is a cyclic permutation of period 6
3. COMPLEMENT: {3,6,9≡0} = non-units = multiples of 3 = QA singularity set
4. DIAGONAL: opposite pairs sum to 9: (1,8), (2,7), (4,5)
5. PARITY: three even {2,4,8} D-sum to 5 (odd); three odd {1,5,7} D-sum to 4 (even)
6. GENERATOR: 2 is a primitive root mod 9 (generates all units by powers)

Source: Grant/Ghannam Philomath Ch 1 (doubling cycle, Yin-Yang completion);
Iverson QA mod-9 orbit structure ({3,6,9} = singularity).

Checks: SP_1 (schema), SP_GROUP (all 6 elements coprime to 9),
SP_CYCLE (doubling mod 9 has period 6), SP_COMP ({3,6,0} = complement),
SP_DIAG (opposite pairs sum to 9), SP_PAR (even D-sum odd, odd D-sum even),
SP_W (all 6 elements witnessed), SP_F (doubling from 1 present).
"""

import json
import os
import sys
from math import gcd


SCHEMA = "QA_SEPTENARY_CERT.v1"
SEPTENARY = frozenset({1, 2, 4, 5, 7, 8})
COMPLEMENT = frozenset({0, 3, 6})  # mod 9: 0≡9


def validate(cert, *, collect_errors=True):
    errors = []
    warnings = []

    def err(chk, msg):
        errors.append({"check_id": chk, "message": msg})

    if cert.get("schema_version") != SCHEMA:
        err("SP_1", f"schema_version must be {SCHEMA}")

    # --- SP_GROUP: declared septenary set = units mod 9 ---
    decl_set = cert.get("septenary_set")
    if decl_set is not None:
        decl_fs = frozenset(decl_set)
        # Verify = (Z/9Z)*
        units = frozenset(k for k in range(1, 9) if gcd(k, 9) == 1)
        if decl_fs != units:
            err("SP_GROUP", f"declared set {sorted(decl_fs)} != (Z/9Z)* = {sorted(units)}")
        if decl_fs != SEPTENARY:
            err("SP_GROUP", f"declared set != septenary {sorted(SEPTENARY)}")

    # --- SP_CYCLE: doubling mod 9 cycle ---
    cycle = cert.get("doubling_cycle", [])
    if len(cycle) > 0:
        # Verify each step is ×2 mod 9
        for i in range(len(cycle) - 1):
            expected = (cycle[i] * 2) % 9
            if cycle[i + 1] != expected:
                err("SP_CYCLE", f"cycle step {i}: {cycle[i]}×2 mod 9 = {expected} != {cycle[i+1]}")
        # Verify period = 6 (returns to start)
        if len(cycle) >= 2:
            last_next = (cycle[-1] * 2) % 9
            if last_next != cycle[0]:
                err("SP_CYCLE", f"cycle doesn't close: {cycle[-1]}×2 mod 9 = {last_next} != {cycle[0]}")
        # Verify length
        decl_period = cert.get("cycle_period")
        if decl_period is not None and decl_period != len(cycle):
            err("SP_CYCLE", f"declared period {decl_period} != cycle length {len(cycle)}")
        if len(cycle) != 6:
            err("SP_CYCLE", f"doubling cycle length {len(cycle)} != 6")

    # --- SP_COMP: complement set ---
    decl_comp = cert.get("complement_set")
    if decl_comp is not None:
        decl_cs = frozenset(decl_comp)
        if decl_cs != COMPLEMENT:
            err("SP_COMP", f"complement declared {sorted(decl_cs)} != {sorted(COMPLEMENT)}")

    # --- SP_DIAG: diagonal pairs sum to 9 ---
    diag_pairs = cert.get("diagonal_pairs", [])
    for i, pair in enumerate(diag_pairs):
        a, b = pair
        if a + b != 9:
            err("SP_DIAG", f"diagonal_pair[{i}] ({a},{b}): sum={a+b} != 9")
        if a not in SEPTENARY or b not in SEPTENARY:
            err("SP_DIAG", f"diagonal_pair[{i}] ({a},{b}): not both in septenary set")

    if len(diag_pairs) < 3:
        warnings.append("SP_DIAG: fewer than 3 diagonal pairs declared")

    # --- SP_PAR: parity cross-sums ---
    parity = cert.get("parity_sums", {})
    even_sum = parity.get("even_sum")
    odd_sum = parity.get("odd_sum")
    # Even elements of septenary: {2,4,8}, sum=14, D(14)=5 (odd)
    # Odd elements: {1,5,7}, sum=13, D(13)=4 (even)
    if even_sum is not None:
        actual_even = sum(k for k in SEPTENARY if k % 2 == 0)  # 2+4+8=14
        if even_sum != actual_even:
            err("SP_PAR", f"even_sum declared {even_sum} != {actual_even}")
    if odd_sum is not None:
        actual_odd = sum(k for k in SEPTENARY if k % 2 == 1)  # 1+5+7=13
        if odd_sum != actual_odd:
            err("SP_PAR", f"odd_sum declared {odd_sum} != {actual_odd}")

    # --- SP_W: all 6 elements witnessed ---
    witnessed = set()
    for c in cycle:
        witnessed.add(c)
    if len(witnessed) < 6:
        err("SP_W", f"only {len(witnessed)} elements witnessed in cycle, need 6")

    # --- SP_F: starts from 1 ---
    if len(cycle) > 0 and cycle[0] != 1:
        err("SP_F", f"cycle should start from 1, starts from {cycle[0]}")

    return {"ok": len(errors) == 0, "errors": errors, "warnings": warnings}


def self_test():
    here = os.path.dirname(os.path.abspath(__file__))
    fix_dir = os.path.join(here, "fixtures")
    expected = {
        "sp_pass_group_structure.json": True,
        "sp_pass_qa_connection.json": True,
    }
    results = []
    for fname, should_pass in expected.items():
        path = os.path.join(fix_dir, fname)
        with open(path) as f:
            cert = json.load(f)
        res = validate(cert)
        ok = res["ok"] == should_pass
        results.append({
            "fixture": fname,
            "expected_pass": should_pass,
            "actual_pass": res["ok"],
            "ok": ok,
            "errors": res["errors"],
            "warnings": res["warnings"],
        })
    return results


if __name__ == "__main__":
    if "--self-test" in sys.argv:
        results = self_test()
        all_ok = all(r["ok"] for r in results)
        print(json.dumps({"ok": all_ok, "results": results}, indent=2))
    elif len(sys.argv) > 1:
        with open(sys.argv[1]) as f:
            cert = json.load(f)
        print(json.dumps(validate(cert), indent=2))
    else:
        print("Usage: python qa_septenary_cert_validate.py [--self-test | <fixture.json>]")
