#!/usr/bin/env python3
QA_COMPLIANCE = "cert_validator — QA Pythagorean triple as survey unit; exact Fraction spreads; Area=6L; no float QA state"
"""
QA Rational Surveying Cert [310] — validator

Primary sources:
  Iverson, B. (1975-1996) Quantum Arithmetic vols 1-2 (QA-1, QA-2)
  Wildberger, N.J. (2005) Divine Proportions: Rational Trigonometry, Wild Egg Books,
    ISBN 978-0-9757492-0-8
  Hardy, G.H. and Wright, E.M. (2008) An Introduction to the Theory of Numbers, Oxford,
    ISBN 978-0-19-921986-5, Ch.XIII (Pythagorean triples, primitive generation)

QA mapping: Every integer-sided right triangle is generated by a QA base pair (b,e)
via the squaring map (unbounded integer arithmetic, no modular reduction):
  d = b + e                     (derived coord)
  a = b + 2*e  (= d + e)        (derived coord)
  C = 2*d*e                     (short leg — the even leg)
  F = d*d - e*e  (= b*a)        (long leg)
  G = d*d + e*e  (= Gaussian norm N(d+ie))  (hypotenuse)
  L = d*e*(d*d - e*e) / 6       (cubic QA identity)

This is Euclid's Pythagorean parametrization expressed in QA variables.
The QA system is the generator algebra for all integer-sided right triangles.

Five claims (all exact integer / Fraction arithmetic, no floats in QA layer):
  C1  Pythagorean identity: C^2 + F^2 = G^2 for all (b,e) in {1,...,24}^2 (576 cases).
      Universal algebraic identity; confirmed numerically for all test pairs.
  C2  Area = 6L: the right-triangle area (C*F/2) = 6*L where L = d*e*(d^2-e^2)/6.
      The area of the integer surveying triangle equals 6 times the cubic QA identity L.
      Equivalently C*F = 12*L exactly for all (b,e).
  C3  Primitivity criterion: gcd(C,F,G)=1 (primitive triple) iff gcd(b,e)=1 AND b is odd.
      Euclid: primitive iff gcd(d,e)=1 AND d,e have different parities;
      since gcd(d,e)=gcd(b,e) and d-e=b, d,e have different parities iff b is odd.
      Verified exhaustively over {1,...,24}^2, zero exceptions.
  C4  Exact rational spreads: the three Wildberger angle-spreads of the QA right triangle
      are all exact Fractions — s_P = F^2/G^2, s_Q = C^2/G^2, s_R = 1 — with s_P + s_Q = 1
      and both s_P, s_Q strictly in (0,1). No irrational angle or pi appears in the QA layer.
  C5  Theorem NT boundary: the bearing (arctan(F/C)) is a transcendental real number and
      lives in the observer layer only; the Wildberger spread s_P = F^2/G^2 replaces it
      at the QA-compatible measurement interface. The QA layer is purely discrete integer
      arithmetic; the bearing is an observer projection that never re-enters QA logic.
"""

import json
import sys
from fractions import Fraction
from math import gcd, atan2, pi as _pi


def pyth_triple(b, e):
    """Return (C, F, G, L) for unbounded QA pair (b,e). All exact integers."""
    d = b + e
    a = b + 2 * e   # = d + e
    C = 2 * d * e
    F = d * d - e * e   # = b * a
    G = d * d + e * e
    L_num = d * e * F   # = d*e*(d^2-e^2) = d*e*b*a; 6 always divides this
    L = L_num // 6
    return C, F, G, L


test_pairs = [(b, e) for b in range(1, 25) for e in range(1, 25)]   # 576 pairs

checks = {}
passed = 0
failed = 0


# ── C1  Pythagorean identity ──────────────────────────────────────────────────
ok_c1 = True
c1_fail = None
for b, e in test_pairs:
    C, F, G, _ = pyth_triple(b, e)
    if C * C + F * F != G * G:
        ok_c1 = False
        c1_fail = (b, e)
        break
checks["C1_pythagorean_identity_C2_plus_F2_eq_G2"] = "PASS" if ok_c1 else "FAIL"
if ok_c1: passed += 1
else:     failed += 1


# ── C2  Area = 6L ─────────────────────────────────────────────────────────────
ok_c2 = True
c2_fail = None
for b, e in test_pairs:
    C, F, G, L = pyth_triple(b, e)
    # Area = C*F/2 = 6L  <=>  C*F = 12*L
    if C * F != 12 * L:
        ok_c2 = False
        c2_fail = (b, e)
        break
checks["C2_area_equals_6L_triangle_cubic_identity"] = "PASS" if ok_c2 else "FAIL"
if ok_c2: passed += 1
else:     failed += 1


# ── C3  Primitivity criterion ─────────────────────────────────────────────────
ok_c3 = True
c3_mismatches = []
for b, e in test_pairs:
    C, F, G, _ = pyth_triple(b, e)
    actual_primitive = (gcd(gcd(C, F), G) == 1)
    pred_primitive   = (gcd(b, e) == 1 and b % 2 == 1)
    if actual_primitive != pred_primitive:
        ok_c3 = False
        c3_mismatches.append((b, e, actual_primitive, pred_primitive))
checks["C3_primitivity_criterion_gcd1_and_b_odd"] = "PASS" if ok_c3 else "FAIL"
if ok_c3: passed += 1
else:     failed += 1


# ── C4  Exact rational spreads ────────────────────────────────────────────────
ok_c4 = True
c4_fail = None
for b, e in test_pairs:
    C, F, G, _ = pyth_triple(b, e)
    G_sq = G * G
    s_P = Fraction(F * F, G_sq)    # spread at P-vertex (opposite the C-leg)
    s_Q = Fraction(C * C, G_sq)    # spread at Q-vertex (opposite the F-leg)
    if not (isinstance(s_P, Fraction) and isinstance(s_Q, Fraction)):
        ok_c4 = False; c4_fail = (b, e, "not Fraction"); break
    if s_P + s_Q != Fraction(1):
        ok_c4 = False; c4_fail = (b, e, "sum != 1"); break
    if not (Fraction(0) < s_P < Fraction(1)):
        ok_c4 = False; c4_fail = (b, e, "s_P out of (0,1)"); break
    if not (Fraction(0) < s_Q < Fraction(1)):
        ok_c4 = False; c4_fail = (b, e, "s_Q out of (0,1)"); break
checks["C4_exact_rational_spreads_sP_plus_sQ_eq_1"] = "PASS" if ok_c4 else "FAIL"
if ok_c4: passed += 1
else:     failed += 1


# ── C5  Theorem NT: bearing is observer, spread is exact ─────────────────────
# On the five canonical Heino sets: arctan(F/C) is float (observer);
# Wildberger spread F^2/G^2 is exact Fraction (QA layer).
heino = [(1, 1), (1, 2), (1, 3), (2, 3), (3, 5)]
ok_c5 = True
heino_data = []
for b, e in heino:
    C, F, G, _ = pyth_triple(b, e)
    bearing_obs = atan2(F, C)               # float — observer projection only
    spread_qa   = Fraction(F * F, G * G)    # exact Fraction — QA measurement layer
    if not isinstance(spread_qa, Fraction):
        ok_c5 = False; break
    if not isinstance(bearing_obs, float):
        ok_c5 = False; break
    heino_data.append({
        "be":              [b, e],
        "CFG":             [C, F, G],
        "spread_exact":    str(spread_qa),
        "bearing_over_pi": bearing_obs / _pi,
    })
checks["C5_theorem_nt_bearing_observer_spread_exact"] = "PASS" if ok_c5 else "FAIL"
if ok_c5: passed += 1
else:     failed += 1


# ── witness values ─────────────────────────────────────────────────────────────
C11, F11, G11, L11 = pyth_triple(1, 1)    # (4, 3, 5) — unit triangle
C12, F12, G12, L12 = pyth_triple(1, 2)    # (12, 5, 13) — perimeter=area pair
C23, F23, G23, L23 = pyth_triple(2, 3)    # (30, 16, 34) = 2*(15,8,17)

result = {
    "ok":              failed == 0,
    "passed":          passed,
    "failed":          failed,
    "checks":          checks,
    "test_pair_count": len(test_pairs),
    "c1_fail":         list(c1_fail) if c1_fail else None,
    "c2_fail":         list(c2_fail) if c2_fail else None,
    "c3_mismatches":   c3_mismatches[:5],
    "c4_fail":         list(c4_fail) if c4_fail else None,
    "heino_sets":      heino_data,
    "witness_1_1":     {"CFG": [C11, F11, G11], "L": L11, "area": C11 * F11 // 2},
    "witness_1_2":     {"CFG": [C12, F12, G12], "L": L12, "area": C12 * F12 // 2},
    "witness_2_3":     {"CFG": [C23, F23, G23], "L": L23, "area": C23 * F23 // 2},
}
print(json.dumps(result, indent=2))
if failed:
    sys.exit(1)
