#!/usr/bin/env python3
"""
QA Diadic Inner Structure Cert [317] -- validator

Primary sources:
  Iverson, B. (1975-1996) Quantum Arithmetic vol 1, QA-1, pp.2-3, 53-56.
    ("Much more research and study is in order to learn the methods.")
  Chace, A.B. (1927) The Rhind Mathematical Papyrus, MAA, Vol.1-2.
  Gillings, R.J. (1972) Mathematics in the Time of the Pharaohs, MIT Press.

Discovery context: continuation of cert [316] (Double Quantum Number).
The cert [316] flagged 4-term inner QN origin as open. This cert certifies
the structural resolution found by computational investigation.

KEY RESULT: The female of the Fibonacci seed BEDA generates the inner
decomposition for 5 of the 8 four-term Rhind entries.

FIBONACCI SEED BEDA: (b=1, e=1, d=2, a=3) -- the smallest non-trivial QN.
  Pythagorean triple: C=4, F=3, G=5 (the 3-4-5 triple).

FEMALE FIBONACCI SEED BEDA: (b=2, e=1, d=3, a=4) via the female transform
  (b,e,d,a) -> (2e, b, a, 2d). All 7 elements: {b,e,d,a,C,F,G}={2,1,3,4,6,8,10}.

GENERATOR FORMULA for 4-term Rhind entries (7 of 8):
  Given a 3-element inner set {c1,c2,c3} with L=lcm(c1,c2,c3):
  n = 2L - (L/c1 + L/c2 + L/c3) = 2L - sum(L//ci)
  Then: 2/n = 1/L + 1/(c1*n) + 1/(c2*n) + 1/(c3*n).

FEMALE FIBONACCI SEED ELEMENTS: {b=2, e=1, d=3, a=4, C=6, F=8, G=10}.
The five 4-term entries generated by 3-element subsets of this set:
  n=29:  inner {b,C,F} = {2,6,8},    L=24, n=48-19=29
  n=61:  inner {a,F,G} = {4,8,10},   L=40, n=80-19=61
  n=79:  inner {d,a,G} = {3,4,10},   L=60, n=120-41=79
  n=89:  inner {a,C,G} = {4,6,10},   L=60, n=120-31=89
  n=101: inner {b,d,C} = {2,3,6},    L=6,  degenerate (inner sum=1, p=n)

MALE-FEMALE BEDA PAIRS generating the remaining 3 entries:
  Male (3,2,5,7)   inner {b,e,a} = {2,3,7} -> n=43
  Female (4,3,7,10) inner {b,e,a} = {3,4,10} -> n=79 (also covered above)
  Male (1,1,2,3)   inner {a,C,G} = {3,4,5} -> n=73
  Male (3,1,4,5)   inner {b,d,a} = {3,4,5} -> n=73 (same inner, different BEDA)
  Female (4,1,5,6) inner {b,d,a} = {4,5,6} -> n=83

n=101 SPECIAL: inner sum = 1/2+1/3+1/6 = 1, the unique 3-term unit fraction
representation of 1 with distinct denominators. p=n=101 (prime), degenerate.

Five claims:
  C1  Generator formula: for each of the 7 standard 4-term entries
      n in {29,43,61,73,79,83,89}, n=2*lcm(c1,c2,c3)-sum(lcm//ci) exactly,
      and 2/n=1/lcm+1/(c1*n)+1/(c2*n)+1/(c3*n) as exact Fraction.
  C2  Female Fibonacci seed: BEDA(2,1,3,4) is the female of BEDA(1,1,2,3)
      via transform (b,e,d,a)->(2e,b,a,2d); its full element set
      {b,e,d,a,C,F,G}={2,1,3,4,6,8,10} generates the inner set for 5 entries
      {n=29,61,79,89,101} as 3-element subsets of this set.
  C3  Male-female BEDA pairs: male (3,2,5,7) generates inner {2,3,7} for n=43;
      female (4,3,7,10)=transform of (3,2,5,7) generates inner {3,4,10} for n=79;
      n=73 is generated by BOTH male (1,1,2,3) (inner {a,C,G}) AND (3,1,4,5)
      (inner {b,d,a}); female (4,1,5,6) of male (1,2,3,5) generates {4,5,6} for n=83.
  C4  n=101 uniqueness: inner sum=1 has exactly one representation as a sum of 3
      distinct unit fractions: 1/2+1/3+1/6=1; p=n is the only prime n in Rhind
      range where the 4-term decomposition uses p=n itself as first denominator.
  C5  Theorem NT: scribal choice of which subset from the female Fibonacci seed
      and which BEDA variant to use are observer projections; the BEDA element
      sets, subset identifications, generator formula, and female transform are
      the discrete QA claims.
"""

QA_COMPLIANCE = (
    "cert_validator -- BEDA identities (d=b+e, a=b+2e, a=d+e); "
    "female transform (b,e,d,a)->(2e,b,a,2d) verified; "
    "Fraction arithmetic for all 4-term decompositions; "
    "Theorem NT: scribal subset choice observer"
)

import json
import sys
from fractions import Fraction
from functools import reduce
from math import gcd, lcm as math_lcm
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))


def lcm_of(*args):
    return reduce(math_lcm, args)


def beda(b, e):
    return b, e, b + e, b + 2 * e


def pyth(b, e):
    _, _, d, a = beda(b, e)
    return 2 * d * e, b * a, d * d + e * e   # C, F, G


def female(b, e, d, a):
    """Female transform: (b,e,d,a) -> (2e, b, a, 2d)."""
    fb, fe = 2 * e, b
    fd, fa = beda(fb, fe)[2], beda(fb, fe)[3]
    return fb, fe, fd, fa


def generator_n(ci):
    L = lcm_of(*ci)
    return 2 * L - sum(L // c for c in ci), L


# ── Rhind 4-term data (Chace 1927) ──────────────────────────────────────────
RHIND_4 = {
    29:  (24,  58,  174,  232),
    43:  (42,  86,  129,  301),
    61:  (40, 244,  488,  610),
    73:  (60, 219,  292,  365),
    79:  (60, 237,  316,  790),
    83:  (60, 332,  415,  498),
    89:  (60, 356,  534,  890),
    101: (101, 202,  303,  606),
}

# Inner sets by n (= ds[i]//n for i>0)
INNER = {n: tuple(sorted(d // n for d in ds[1:])) for n, ds in RHIND_4.items()}

# Female Fibonacci seed elements
FFB, FFE, FFD, FFA = 2, 1, 3, 4
FFC, FFF, FFG = pyth(FFB, FFE)   # C=6, F=8, G=10
FF_ELEMENTS = frozenset({FFB, FFE, FFD, FFA, FFC, FFF, FFG})
# = frozenset({1,2,3,4,6,8,10})

# Entries covered by female Fibonacci seed (3-elem subsets of FF_ELEMENTS)
FF_COVERED = {29: {2, 6, 8},    # {b,C,F}
              61: {4, 8, 10},   # {a,F,G}
              79: {3, 4, 10},   # {d,a,G}
              89: {4, 6, 10},   # {a,C,G}
              101: {2, 3, 6}}   # {b,d,C} -- degenerate

checks = {}
passed = 0
failed = 0


# C1 -- Generator formula: n=2L-Σ(L/ci), 2/n exact for the 7 standard entries
ok_c1 = True
for n, ds in RHIND_4.items():
    if n == 101:
        continue   # degenerate case handled in C4
    ci = [d // n for d in ds[1:]]
    formula_n, L = generator_n(ci)
    if formula_n != n:
        ok_c1 = False
    total = Fraction(1, L) + sum(Fraction(1, c * n) for c in ci)
    if total != Fraction(2, n):
        ok_c1 = False

checks["C1_generator_formula_7_standard_entries_exact_fraction"] = "PASS" if ok_c1 else "FAIL"
if ok_c1: passed += 1
else:     failed += 1


# C2 -- Female Fibonacci seed: transform verified; 5 inner sets are subsets
ok_c2 = True

# Female transform of (1,1,2,3) gives (2,1,3,4)
b0, e0, d0, a0 = beda(1, 1)
fb, fe, fd, fa = female(b0, e0, d0, a0)
if (fb, fe, fd, fa) != (FFB, FFE, FFD, FFA):
    ok_c2 = False

# Verify (2,1,3,4) is a valid BEDA tuple
_, _, dcheck, acheck = beda(FFB, FFE)
if dcheck != FFD or acheck != FFA:
    ok_c2 = False

# Verify C,F,G values
C_ff, F_ff, G_ff = pyth(FFB, FFE)
if (C_ff, F_ff, G_ff) != (FFC, FFF, FFG):
    ok_c2 = False

# Each inner set for n in FF_COVERED is a subset of FF_ELEMENTS
for n, expected in FF_COVERED.items():
    if not expected.issubset(FF_ELEMENTS):
        ok_c2 = False
    if frozenset(INNER[n]) != expected:
        ok_c2 = False

# Generator formula works for n in {29,61,79,89} (not 101 — degenerate)
for n in (29, 61, 79, 89):
    ci = list(FF_COVERED[n])
    formula_n, _ = generator_n(ci)
    if formula_n != n:
        ok_c2 = False

checks["C2_female_fibonacci_seed_covers_5_entries"] = "PASS" if ok_c2 else "FAIL"
if ok_c2: passed += 1
else:     failed += 1


# C3 -- Male-female pairs: (3,2,5,7)->(4,3,7,10) for n=43/79;
#        (1,1,2,3)/{3,4,5} and (3,1,4,5)/{3,4,5} both for n=73;
#        (4,1,5,6)={b,d,a} for n=83
ok_c3 = True

# Male (3,2,5,7) -> inner {b,e,a}={2,3,7} -> n=43
b,e,d,a = beda(3,2)
if frozenset({b,e,a}) != frozenset(INNER[43]):
    ok_c3 = False
# Female of (3,2,5,7) = (4,3,7,10)
fb43,fe43,fd43,fa43 = female(b,e,d,a)
if (fb43,fe43,fd43,fa43) != beda(fb43,fe43)[:4]:
    ok_c3 = False
# Its {b,e,a} gives inner for n=79
if frozenset({fb43,fe43,fa43}) != frozenset(INNER[79]):
    ok_c3 = False

# BEDA(1,1,2,3): inner {a,C,G}={3,4,5} -> n=73
b73a,e73a,d73a,a73a = beda(1,1)
C73a,F73a,G73a = pyth(1,1)
if frozenset({a73a,C73a,G73a}) != frozenset(INNER[73]):
    ok_c3 = False
# BEDA(3,1,4,5): inner {b,d,a}={3,4,5} -> n=73 (same inner set)
b73b,e73b,d73b,a73b = beda(3,1)
if frozenset({b73b,d73b,a73b}) != frozenset(INNER[73]):
    ok_c3 = False
# Both give the same inner set
if frozenset({a73a,C73a,G73a}) != frozenset({b73b,d73b,a73b}):
    ok_c3 = False

# Female of (1,2,3,5) = (4,1,5,6): inner {b,d,a}={4,5,6} -> n=83
b12,e12,d12,a12 = beda(1,2)
fb83,fe83,fd83,fa83 = female(b12,e12,d12,a12)
if frozenset({fb83,fd83,fa83}) != frozenset(INNER[83]):
    ok_c3 = False

checks["C3_male_female_pairs_n43_79_73_83"] = "PASS" if ok_c3 else "FAIL"
if ok_c3: passed += 1
else:     failed += 1


# C4 -- n=101: inner sum=1; unique 3-term distinct unit fraction rep of 1;
#         2/101 = (1/101)*(1+1/2+1/3+1/6) = 2/101 exactly
ok_c4 = True

inner_101 = list(INNER[101])
inner_sum_101 = sum(Fraction(1, c) for c in inner_101)
if inner_sum_101 != Fraction(1):
    ok_c4 = False

# Verify it matches Rhind: 2/101 = 1/101 + 1/202 + 1/303 + 1/606
total_101 = sum(Fraction(1, d) for d in RHIND_4[101])
if total_101 != Fraction(2, 101):
    ok_c4 = False

# Uniqueness: only one 3-term representation of 1 as distinct unit fractions
# (besides (2,4,4) and (3,3,3) which have repeats): must be (2,3,6)
unique_solutions = []
for a in range(2, 20):
    for b in range(a + 1, 100):
        rem = Fraction(1) - Fraction(1, a) - Fraction(1, b)
        if rem > 0 and rem.numerator == 1:
            c = rem.denominator
            if c > b:
                unique_solutions.append((a, b, c))
if unique_solutions != [(2, 3, 6)]:
    ok_c4 = False

checks["C4_n101_inner_sum_1_unique_3term_representation"] = "PASS" if ok_c4 else "FAIL"
if ok_c4: passed += 1
else:     failed += 1


# C5 -- Theorem NT: all BEDA/Pythagorean data are integers; no float
ok_c5 = True
for val in [FFB, FFE, FFD, FFA, FFC, FFF, FFG]:
    if not isinstance(val, int) or val <= 0:
        ok_c5 = False
# FF_ELEMENTS is a frozenset of integers
if not all(isinstance(x, int) and x > 0 for x in FF_ELEMENTS):
    ok_c5 = False
# Generator formula outputs are integers
for n in (29, 61, 79, 89):
    ci = list(FF_COVERED[n])
    fn, L = generator_n(ci)
    if not isinstance(fn, int) or not isinstance(L, int):
        ok_c5 = False
# All Fraction sums are Fraction type, not float
for n, ds in RHIND_4.items():
    val = sum(Fraction(1, d) for d in ds)
    if not isinstance(val, Fraction):
        ok_c5 = False

checks["C5_theorem_nt_all_beda_pyth_data_int_no_float"] = "PASS" if ok_c5 else "FAIL"
if ok_c5: passed += 1
else:     failed += 1


print(json.dumps(checks, indent=2))
print(f"\nTotal: {passed} PASS, {failed} FAIL")
if failed:
    sys.exit(1)
